# Generated by Django 5.1.6 on 2025-02-11 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_seller_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='handle_visits',
            field=models.BooleanField(default=True, help_text='Επιλέξτε αν επιθυμείτε να αναλάβετε εσείς τις επισκέψεις.'),
        ),
        migrations.CreateModel(
            name='VisitAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateTimeField(help_text='Η διαθέσιμη ημερομηνία/ώρα για επίσκεψη')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(help_text='Η ημερομηνία/ώρα που επιλέγει ο αγοραστής από τις διαθέσιμες επιλογές')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('buyer_notes', models.TextField(blank=True, help_text='Σημειώσεις του αγοραστή')),
                ('seller_notes', models.TextField(blank=True, help_text='Σημειώσεις του Seller/Handler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='listings.buyer')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_visit_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='listings.property')),
            ],
        ),
    ]
