# Generated by Django 5.1.6 on 2025-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_seller_handle_visits_visitavailability_visitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Αιτιολόγηση ακύρωσης (εάν υπάρξει)'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='delegated',
            field=models.BooleanField(default=False, help_text='True αν το αίτημα πρέπει να χειριστείται από τους διαχειριστές (όταν ο Seller δεν αναλαμβάνει τις επισκέψεις)'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED_BY_BUYER', 'Cancelled by Buyer'), ('CANCELLED_BY_SELLER', 'Cancelled by Seller')], default='PENDING', max_length=20),
        ),
    ]
