# Generated by Django 5.1.6 on 2025-02-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_supportticket_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBuyerAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(help_text='True αν ο αγοραστής αποδέχθηκε, False αν απορρίφθηκε, Null αν δεν έχει αποφασιστεί.', null=True)),
                ('lock_until', models.DateTimeField(blank=True, help_text="Αν απορριφθεί, το ακίνητο 'κλειδώνεται' για αυτόν τον αγοραστή μέχρι αυτήν την ημερομηνία.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_associations', to='listings.agent')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_associations', to='listings.buyer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_buyer_associations', to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to='listings.buyer')),
            ],
        ),
    ]
