# Generated by Django 5.1.6 on 2025-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_agentbuyerassociation_temp_buyer_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
