# Generated by Django 5.1.6 on 2025-02-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_buyer_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbuyerassociation',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_associations', to='listings.buyer'),
        ),
    ]
